Sync with Debian

diff --git a/debian/zabbix-java-gateway.init b/debian/zabbix-java-gateway.init
--- a/debian/zabbix-java-gateway.init
+++ b/debian/zabbix-java-gateway.init
@@ -1,103 +1,107 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          zabbix-java-gateway
-# Required-Start:    $remote_fs $network 
+# Required-Start:    $remote_fs $network
 # Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start zabbix-java-gateway daemon
+# Description: Control zabbix-java-gateway daemon
 ### END INIT INFO
 
-set -e
+NAME=zabbix-java-gateway
+DAEMON=/usr/bin/java
+# Exit if executable is not installed
+[ -x $DAEMON ] || exit 0
 
-NAME=zabbix_java_gateway
-DAEMON=usr/share/zabbix-java
-DESC="Zabbix java gateway"
-RETRY=15
+DIR=/var/run/zabbix
+PID_FILE=$DIR/$NAME.pid
+RETRY=TERM/30/KILL/5
 
-export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
+#if [ "$(id -u)" -ne 0 ]; then
+#    echo "Error: root privileges are needed to run $0"
+#    exit 1
+#fi
 
-if [ `id -u` -ne 0 ]; then
-        echo "You need root privileges to run this script"
-        exit 1
+# Source Zabbix java gateway configuration file
+. /etc/zabbix/zabbix_java_gateway.conf
+
+ZABBIX_OPTIONS=""
+if [ -n "$PID_FILE" ]; then
+    ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.pidFile=$PID_FILE"
 fi
+if [ -n "$LISTEN_IP" ]; then
+    ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.listenIP=$LISTEN_IP"
+fi
+if [ -n "$LISTEN_PORT" ]; then
+    ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.listenPort=$LISTEN_PORT"
+fi
+if [ -n "$START_POLLERS" ]; then
+    ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.startPollers=$START_POLLERS"
+fi
+if [ -n "$TIMEOUT" ]; then
+    ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.timeout=$TIMEOUT -Dsun.rmi.transport.tcp.responseTimeout=${TIMEOUT}000"
+fi
+DAEMON_ARGS="${JAVA_OPTIONS} -server ${ZABBIX_OPTIONS} -Dlogback.configurationFile=/etc/zabbix/zabbix_java_gateway.logback.xml -Djava.library.path=/usr/lib/jni -jar /usr/sbin/zabbix-java-gateway.jar"
+#COMMAND_LINE="${DAEMON} $DAEMON_ARGS -classpath $CLASSPATH com.zabbix.gateway.JavaGateway"
+
+# Load the VERBOSE setting and other rcS variables
+[ -f /etc/default/rcS ] && . /etc/default/rcS
 
 # define LSB log_* functions.
 . /lib/lsb/init-functions
 
-# Source Zabbix java gateway configuration file
-. /etc/zabbix/settings.sh
+_ev_ () {
+  [ "$VERBOSE" = "no" ] || eval $@
+}
+
+[ -d "$DIR" ] || mkdir "$DIR"
+chown -R zabbix:zabbix "$DIR"
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
 case "$1" in
   start)
-    log_daemon_msg "Starting $DESC" "$NAME"
-
-    JAVA=/usr/bin/java
-
-    JAVA_OPTIONS="-server"
-    if [ -z "$PID_FILE" ]; then
-        JAVA_OPTIONS="$JAVA_OPTIONS -Dlogback.configurationFile=logback-console.xml"
-    fi
-
-    cd $DAEMON
-
-    CLASSPATH="$DAEMON/lib"
-    for jar in `find lib bin -name "*.jar"`; do
-        if [ $jar != *junit* ]; then
-            CLASSPATH="$CLASSPATH:$DAEMON/$jar"
-        fi
-    done
-
-    ZABBIX_OPTIONS=""
-    if [ -n "$PID_FILE" ]; then
-        ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.pidFile=$PID_FILE"
-    fi
-    if [ -n "$LISTEN_IP" ]; then
-        ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.listenIP=$LISTEN_IP"
-    fi
-    if [ -n "$LISTEN_PORT" ]; then
-        ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.listenPort=$LISTEN_PORT"
-    fi
-    if [ -n "$START_POLLERS" ]; then
-        ZABBIX_OPTIONS="$ZABBIX_OPTIONS -Dzabbix.startPollers=$START_POLLERS"
-    fi
-
-    #COMMAND_LINE="$JAVA $JAVA_OPTIONS -classpath $CLASSPATH $ZABBIX_OPTIONS com.zabbix.gateway.JavaGateway"
-    DAEMON_ARGS="$JAVA_OPTIONS -classpath $CLASSPATH $ZABBIX_OPTIONS com.zabbix.gateway.JavaGateway"
-
-    start-stop-daemon --start -b -m -u zabbix -g zabbix -c zabbix -p $PID_FILE --exec $JAVA -- $DAEMON_ARGS
-
-    case "$?" in
-        0) log_end_msg 0 ;;
-        *) log_end_msg 1; exit 1 ;;
-    esac
-	;;
+    start-stop-daemon --start --pidfile $PID_FILE --exec $DAEMON --test --quiet > /dev/null
+    [ $? -ne 0 ] && log_action_msg "$NAME is already running" && exit 0
+    _ev_ log_action_begin_msg \"$NAME starting\"
+    R=$(start-stop-daemon --start --background --make-pidfile --user zabbix --group zabbix --chuid zabbix --pidfile $PID_FILE --exec $DAEMON --oknodo -- ${DAEMON_ARGS} 2>&1) \
+    && _ev_ log_action_end_msg 0 \"$R\" \
+    || _ev_ log_action_end_msg 1 \"$R\"
+  ;;
   stop)
-    log_daemon_msg "Stopping $DESC" "$NAME"
-	start-stop-daemon --oknodo --stop --pidfile $PID_FILE --retry $RETRY
-    case "$?" in
-        0) log_end_msg 0 ;;
-        *) log_end_msg 1; exit 1 ;;
-    esac
-	;;
+    _ev_ log_action_begin_msg "$NAME stopping"
+    R=$(start-stop-daemon --stop --pidfile $PID_FILE --oknodo --retry=$RETRY 2>&1)
+    if [ $? -ne 0 ]; then
+        _ev_ log_action_end_msg 1 \"$R\"
+    else
+        t=5
+        while $0 status >/dev/null; do
+            _ev_ log_action_cont_msg \"[$t]\"
+            t=$(($t-1))
+            if [ $t -ne 0 ]; then
+                sleep 1
+                continue
+            else
+                break
+            fi
+        done
+        $0 status >/dev/null \
+        && _ev_ log_action_end_msg 1 \"still running after 5 sec., unable to stop\" \
+        || _ev_ log_action_end_msg 0 \"$R\"
+    fi
+  ;;
   status)
-   ls -l /proc/`cat $PID_FILE`/exe > /dev/null 2>&1
-   if [ $? -eq 0 ]; then
-       echo "$DESC is running"
-       exit 0
-   else
-       echo "$DESC is NOT running"
-       exit 1
-   fi
-   ;;
+    ## return status 0 if process is running.
+    status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
+  ;;
   restart|force-reload)
-	$0 stop
-	$0 start
-	;;
+    $0 stop
+    $0 status >/dev/null \
+    &&  exit 1  \
+    || $0 start
+  ;;
   *)
-    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+    exit 1
+  ;;
 esac
-
-exit 0
